-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 11:24:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema workDaily
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema workDaily
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workDaily` DEFAULT CHARACTER SET utf8 ;
USE `workDaily` ;

-- -----------------------------------------------------
-- Table `workDaily`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workdaily`.`users`(
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(5) NOT NULL ,
  `email` VARCHAR(60) NOT NULL ,
  `password` CHAR(40) NOT NULL ,
  `type` ENUM('boss','department','group','normal') NOT NULL DEFAULT 'normal',
  `regis_date` DATETIME NOT NULL ,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC ),
  INDEX `login` USING BTREE (`email` ASC ,`password` ASC )
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workDaily`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `workdaily`.`message` (
  `message_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `user` SMALLINT UNSIGNED NOT NULL ,
  `subject` VARCHAR(40),
  `body` VARCHAR(1000) NOT NULL ,
  `send_date` DATETIME NOT NULL ,
  PRIMARY KEY (`message_id`),
  INDEX `subject` (`subject` ASC ),
  INDEX `parent_id_idx` (`parent_id` ASC ),
  INDEX `user_idx` (`user` ASC ),
  CONSTRAINT `user`
  FOREIGN KEY (`user`)
  REFERENCES `workdaily`.`users` (`user_id`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION
)ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
